name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-nginx-web-server:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx-web-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy step
        run: echo "Deploying application..."
